import { colors, fonts, fontSizes, layout } from './tokens';

export const cssVariables: Record<string, string> = {
    '--color-bg-page': colors.background.page,
    '--color-bg-top-bar': colors.background.topBar,
    '--color-bg-surface': colors.background.surface,
    '--color-bg-surface-alt': colors.background.surfaceAlt,
    '--color-bg-row-even': colors.background.rowEven,
    '--color-bg-row-odd': colors.background.rowOdd,
    '--color-bg-row-hover': colors.background.rowHover,
    '--color-bg-table-head': colors.background.tableHead,
    '--color-bg-map': colors.background.map,
    '--color-bg-playback': colors.background.page,
    '--color-bg-fight': colors.background.page,
    '--color-bg-combobox': colors.background.combobox,
    '--color-bg-combobox-hover': colors.ui.comboboxHover,
    '--color-bg-tooltip': colors.background.surfaceAlt,
    '--color-bg-tooltip-overlay': colors.ui.tooltipBg,

    '--color-text-primary': colors.text.primary,
    '--color-text-gold': colors.text.gold,
    '--color-text-muted': colors.text.muted,
    '--color-text-account': colors.text.rune,
    '--color-text-player': colors.text.player,
    '--color-text-other': colors.text.other,
    '--color-text-dps': colors.text.dps,
    '--color-text-damage': colors.text.damage,
    '--color-text-heal': colors.text.heal,
    '--color-text-link': colors.text.link,
    '--color-text-instructions-heading': colors.text.instructionsHeading,
    '--color-text-instructions-link': colors.text.instructionsLink,
    '--color-text-yellow': colors.text.yellow,
    '--color-text-black': colors.background.black,
    '--color-text-white': colors.text.primary,
    '--color-text-icon-hover': colors.text.iconHover,
    '--color-text-medal-gold': colors.medal.gold,

    '--color-border-default': colors.border.default,
    '--color-border-black': colors.border.black,
    '--color-border-white': colors.border.white,

    '--color-switch-tan': colors.switch.tan,

    '--font-body': fonts.body,
    '--font-system': fonts.system,
    '--font-mono': fonts.mono,

    '--font-size-xs': fontSizes.xs,
    '--font-size-sm': fontSizes.sm,
    '--font-size-md': fontSizes.md,
    '--font-size-base': fontSizes.base,
    '--font-size-lg': fontSizes.lg,
    '--font-size-xl': fontSizes.xl,
    '--font-size-responsive-main': fontSizes.responsiveMain,
    '--font-size-recharts-axis': fontSizes.rechartsAxis,
    '--font-size-recharts-pie': fontSizes.rechartsPie,
    '--font-size-performance-title': fontSizes.performanceTitle,
    '--font-size-performance-percent': fontSizes.performancePercent,
    '--font-size-dropdown-fight': fontSizes.dropdownFight,

    '--layout-content-max-width': `${layout.contentMaxWidth}px`,
};
