export const colors = {
    background: {
        page: '#262a2e',
        surface: '#141414',
        surfaceAlt: '#101010',
        surfaceDropdown: '#1f1f1f',
        surfaceMenu: '#1e1e1e',
        surfaceSelected: '#2e2e2e',
        rowEven: '#000000',
        rowOdd: '#101010',
        rowHover: 'rgb(0, 32, 64)',
        tableHead: '#494949',
        tableHeadAlt: '#494945',
        black: '#000000',
        map: '#000',
        hover: '#333',
        progress: '#444',
        combobox: 'white',
        transparent: 'transparent',
    },
    border: {
        default: 'grey',
        black: 'black',
        white: 'white',
    },
    text: {
        primary: '#ffffff',
        gold: '#e5cc80',
        player: '#abd473',
        other: '#b4bdff',
        dps: '#d1fa99',
        damage: 'rgb(92%, 27%, 38%)',
        heal: 'rgb(0, 255, 4)',
        link: '#61dafb',
        instructionsHeading: '#333',
        instructionsLink: '#007bff',
        yellow: 'yellow',
        lightblue: 'lightblue',
        iconHover: '#ccc',
    },
    fight: {
        success: 'rgb(128, 230, 102)',
        failure: 'rgb(230, 128, 102)',
    },
    medal: {
        silver: '#C0C0C0',
        bronze: '#CD7F32',
        gold: 'gold',
    },
    rank: {
        top3: '#e5cc80',
        top10: '#f48cba',
        top20: '#ff8000',
        top100: '#a335ee',
        top200: '#0070dd',
        top500: '#1eff00',
        default: '#9d9d9d',
    },
    chart: {
        attack: '#C69B6D',
        strength: '#C41E3A',
        defence: '#0070DD',
        ranged: '#AAD372',
        magic: '#3FC7EB',
        cursor: '#3c3226',
        meleeVertical: 'rgb(153, 38, 58)',
        rangedVertical: 'rgb(72, 84, 55)',
        magicVertical: 'rgb(28, 95, 115)',
        hitpoints: 'red',
        prayer: 'yellow',
    },
    replay: {
        tabActive: 'rgb(183, 157, 126)',
        tabInactive: 'rgb(115, 101, 89)',
        marker: '#e53333',
        gridBorder: '#999',
    },
    map: {
        marker: '#33b5e5',
    },
    upload: {
        dragActive: '#1e88e5',
        buttonHover: '#f0f0f0',
    },
    dpsMeter: {
        playerHighlight: '#007bff',
    },
    switch: {
        tan: 'tan',
        tanHex: '#D2B48C',
    },
    ui: {
        comboboxHover: 'lightgray',
        tooltipBg: 'rgba(100, 100, 100, 0.8)',
        dividerSubtle: 'rgba(255,255,255,0.12)',
    },
} as const;

export const fonts = {
    body: 'Avenir, Arial, sans-serif',
    system: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    mono: "source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace",
} as const;

export const fontSizes = {
    xs: '12px',
    sm: '13px',
    md: '14px',
    base: '16px',
    lg: '18px',
    xl: '24px',
    topBarLogo: '25px',
    topBarIcon: '28px',
    tableMobile: '14px',
    responsiveMain: 'calc(10px + 2vmin)',
    rechartsAxis: 'calc(12px + 0.8vmin)',
    rechartsPie: 'calc(12px + 0.5vmin)',
    performanceTitle: 'calc(12px + 0.5vmin)',
    performancePercent: 'calc(18px + 2vmin)',
    dropdownFight: 'calc(8px + 1vmin)',
    eventsTableMobile: '12px',
    dpsTable: '13px',
    dpsTableMobile: '12px',
} as const;

export const typography = {
    h1: 'clamp(3.6rem, 10vw, 6rem)',
    h2: 'clamp(2.25rem, 6.25vw, 3.75rem)',
    h3: 'clamp(1.8rem, 5vw, 3rem)',
    h4: 'clamp(1.275rem, 3.5vw, 2.125rem)',
    h5: 'clamp(1rem, 2.5vw, 1.5rem)',
    h6: 'clamp(1rem, 2vw, 1.25rem)',
} as const;
